env:
  browser: true
  node: true
  es6: true
  jquery: true
rules:
  no-console: 0
  no-inner-declarations: 0
  quotes: [2, single]
globals:
  Handlebars: true
  moment: true
extends: eslint:recommended
