name: Linter
on:
  pull_request:
    branches: [ master ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10'
        
    - name: Test
      run: |
        npm install
        npm run test