name: Unstage

on:
  pull_request_target:
    types: [ closed ]
    branches: [ master ]

jobs:
  staging:
    name: Remove Pull Request from Staging
    runs-on: ubuntu-latest

    steps:

    - name: Setup git config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Checkout Staging repo
      uses: actions/checkout@v2
      with:
        repository: AdoptOpenJDK/openjdk-website-staging
        path: openjdk-website-staging
        token: ${{ secrets.ACCESS_TOKEN }}
        ssh-key: ${{ secrets.ADOPT_BOT_SSH_PRIVATE }}

    - run: |
        echo "removing $number"
        cd openjdk-website-staging
        git rm -rf "$PR_NUMBER"
        git commit -m "Remove $PR_NUMBER from staging"
        git push origin gh-pages
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
